name: Test 3
favicon: null
layout_spectrum: 0.6674820613116026
typography_spectrum: 0.16089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090714'
    - '#fcfefd'
    - '#e8b252'
    - '#d38200'
    - '#3e4420'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
