name: Test 3
favicon: null
layout_spectrum: 0.6674820613116026
typography_spectrum: 0.14517222857102752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090714'
    - '#fcfefd'
    - '#e8b252'
    - '#d38200'
    - '#3e4420'
  brandStrength: 0.9162473587784916
  lightness: 0.5763502740301192
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
